language: go
sudo: false
go:
  - 1.8
git:
  depth: 3

install:
  - make install

go_import_path: github.com/nightlegend/apigateway

script:
  - make vet
  - make fmt-check
  - make test  

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ffea2046e25d2006a209
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false